### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id' in line.py

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#95]
Port detection api endpoint produces 500 Internal server error for the following image:

![image](https://user-images.githubusercontent.com/11476842/123660575-666a4080-d7f9-11eb-8c2a-d53d68a91cb3.png)

Stack Trace:
```py
Traceback (most recent call last):
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/umesh/anaconda3/envs/scm/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/umesh/work/design.R/scm/circuit_recognizer/circuit_recognizer/server.py", line 37, in detect_ports
    ports = recognize_ports(image, annotation)
  File "/home/umesh/work/design.R/scm/circuit_recognizer/circuit_recognizer/recognition.py", line 80, in recognize_ports
    r_line.extend(image, [annotation])
  File "/home/umesh/work/design.R/scm/circuit_recognizer/circuit_recognizer/connect/line.py", line 174, in extend
    if annotation.id == src_annotation.id:
AttributeError: 'NoneType' object has no attribute 'id'
```

## Annotations to reproduce the bug:
[annotations-2021-06-28T15_07_15.814Z.zip](https://github.com/symbench/scm/files/6727368/annotations-2021-06-28T15_07_15.814Z.zip)

**Comment by umesh-timalsina** [comment]
Upon further investigation I found that `src_annotation` in the following line is None hence causing the error:
https://github.com/symbench/scm/blob/add7ef66d059334c95118b05443fff82154b34b5/circuit_recognizer/circuit_recognizer/connect/line.py#L173
